name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libsasl2-dev wkhtmltopdf
          python -m pip install --upgrade pip
          pip install cython
          pip install thriftpy
          pip install pandas==1.4.2
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: xvfb-run pytest test/ui
